// <auto-generated />
using System;
using ArsenalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArsenalApi.Migrations
{
    [DbContext(typeof(ArsenalDbContext))]
    [Migration("20260422230141_AddGearItemTargetQuantity")]
    partial class AddGearItemTargetQuantity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArsenalApi.Models.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Divisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gadgets"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vehicles"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Weaponry"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Surveillance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Medical"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tactical"
                        });
                });

            modelBuilder.Entity("ArsenalApi.Models.GearItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("TargetQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("GearItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 1,
                            Name = "Batarangs",
                            Notes = "Standard issue",
                            Quantity = 12,
                            TargetQuantity = 20,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 1,
                            Name = "Grapple Gun",
                            Notes = "Grappling hook launcher",
                            Quantity = 7,
                            TargetQuantity = 15,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 1,
                            Name = "Remote Batarang",
                            Notes = "Remote controlled",
                            Quantity = 23,
                            TargetQuantity = 25,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 2,
                            Name = "Batmobile",
                            Notes = "Primary vehicle",
                            Quantity = 2,
                            TargetQuantity = 8,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 2,
                            Name = "Batwing",
                            Notes = "Aerial vehicle",
                            Quantity = 1,
                            TargetQuantity = 5,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 2,
                            Name = "Batcycle",
                            Notes = "High-speed motorcycle",
                            Quantity = 4,
                            TargetQuantity = 10,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 3,
                            Name = "Explosive Gel",
                            Notes = "Breach tool",
                            Quantity = 8,
                            TargetQuantity = 15,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 3,
                            Name = "Smoke Bombs",
                            Notes = "Smoke screen",
                            Quantity = 45,
                            TargetQuantity = 50,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 3,
                            Name = "EMP Device",
                            Notes = "Electronics disruptor",
                            Quantity = 3,
                            TargetQuantity = 15,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 4,
                            Name = "Bat-Tracker",
                            Notes = "Tracking device",
                            Quantity = 31,
                            TargetQuantity = 35,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 4,
                            Name = "Micro Camera",
                            Notes = "Surveillance camera",
                            Quantity = 18,
                            TargetQuantity = 20,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 4,
                            Name = "Sonar Device",
                            Notes = "Echolocation device",
                            Quantity = 5,
                            TargetQuantity = 10,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 5,
                            Name = "Trauma Kit",
                            Notes = "Field medical kit",
                            Quantity = 14,
                            TargetQuantity = 20,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 5,
                            Name = "Antidote Vials",
                            Notes = "Universal antidote",
                            Quantity = 6,
                            TargetQuantity = 15,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 5,
                            Name = "Nanite Injector",
                            Notes = "Nano-tech healing",
                            Quantity = 19,
                            TargetQuantity = 20,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 6,
                            Name = "Batsuit",
                            Notes = "Primary armor",
                            Quantity = 2,
                            TargetQuantity = 3,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 6,
                            Name = "Kevlar Cape",
                            Notes = "Reinforced cape",
                            Quantity = 22,
                            TargetQuantity = 25,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DivisionId = 6,
                            Name = "Wayne Tech Armor",
                            Notes = "Advanced body armor",
                            Quantity = 9,
                            TargetQuantity = 10,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ArsenalApi.Models.GearItem", b =>
                {
                    b.HasOne("ArsenalApi.Models.Division", "Division")
                        .WithMany("GearItems")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("ArsenalApi.Models.Division", b =>
                {
                    b.Navigation("GearItems");
                });
#pragma warning restore 612, 618
        }
    }
}
